name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Navigate into lab3 directory
      run: cd lab3

    - name: Compile the program
      run: make main

    - name: Run the program
      run: make run

    - name: Clean up build artifacts
      run: make clean
