name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./lab3
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile the program
      run: make main
        
    - name: Run the program
      run: make run

    - name: Clean up build artifacts
      run: make clean
